import { Connection, PublicKey, Keypair, SystemProgram, Transaction } from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import { Program, AnchorProvider, BN } from '@coral-xyz/anchor';
import bs58 from 'bs58';

// Program ID - replace with actual deployed program ID
const PROGRAM_ID = new PublicKey(process.env.PROGRAM_ID || 'BLBDmktYourProgramIdHere11111111111111111111');

// IDL will be generated by Anchor build
// For now, define minimal interface
export interface BillboardMarketIDL {
  version: string;
  name: string;
  instructions: unknown[];
  accounts: unknown[];
}

export interface CampaignAccount {
  campaignId: BN;
  sponsor: PublicKey;
  creator: PublicKey;
  amount: BN;
  duration: BN;
  state: CampaignState;
  startTs: BN;
  endTs: BN;
  bump: number;
  vaultBump: number;
}

export type CampaignState =
  | { deposited: Record<string, never> }
  | { approved: Record<string, never> }
  | { verifying: Record<string, never> }
  | { live: Record<string, never> }
  | { expired: Record<string, never> }
  | { refunded: Record<string, never> }
  | { canceledHard: Record<string, never> };

export function getCampaignStateString(state: CampaignState): string {
  if ('deposited' in state) return 'DEPOSITED';
  if ('approved' in state) return 'APPROVED';
  if ('verifying' in state) return 'VERIFYING';
  if ('live' in state) return 'LIVE';
  if ('expired' in state) return 'EXPIRED';
  if ('refunded' in state) return 'REFUNDED';
  if ('canceledHard' in state) return 'CANCELED_HARD';
  return 'UNKNOWN';
}

/**
 * Derive Campaign PDA
 */
export function getCampaignPDA(campaignId: bigint): [PublicKey, number] {
  const campaignIdBN = new BN(campaignId.toString());
  return PublicKey.findProgramAddressSync(
    [Buffer.from('campaign'), campaignIdBN.toArrayLike(Buffer, 'le', 8)],
    PROGRAM_ID
  );
}

/**
 * Derive Vault PDA
 */
export function getVaultPDA(campaignId: bigint): [PublicKey, number] {
  const campaignIdBN = new BN(campaignId.toString());
  return PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), campaignIdBN.toArrayLike(Buffer, 'le', 8)],
    PROGRAM_ID
  );
}

/**
 * Get platform authority keypair from environment
 */
export function getPlatformAuthority(): Keypair {
  const keypairStr = process.env.PLATFORM_AUTHORITY_KEYPAIR;
  if (!keypairStr) {
    throw new Error('PLATFORM_AUTHORITY_KEYPAIR environment variable is required');
  }
  
  try {
    // Try to decode as base58
    const decoded = bs58.decode(keypairStr);
    return Keypair.fromSecretKey(decoded);
  } catch {
    // Try to parse as JSON array
    const secretKey = JSON.parse(keypairStr);
    return Keypair.fromSecretKey(Uint8Array.from(secretKey));
  }
}

/**
 * Get Solana connection
 */
export function getConnection(): Connection {
  const rpcUrl = process.env.SOLANA_RPC_URL || 'http://localhost:8899';
  return new Connection(rpcUrl, 'confirmed');
}

/**
 * Billboard Market client for server-side operations
 */
export class BillboardMarketClient {
  private connection: Connection;
  private platformAuthority: Keypair;

  constructor() {
    this.connection = getConnection();
    this.platformAuthority = getPlatformAuthority();
  }

  /**
   * Set campaign to VERIFYING state
   */
  async setVerifying(campaignId: bigint): Promise<string> {
    const [campaignPda] = getCampaignPDA(campaignId);

    // Build instruction manually since we don't have the full IDL loaded
    const ix = await this.buildPlatformSetVerifyingIx(campaignPda);
    
    const tx = new Transaction().add(ix);
    tx.feePayer = this.platformAuthority.publicKey;
    tx.recentBlockhash = (await this.connection.getLatestBlockhash()).blockhash;
    
    tx.sign(this.platformAuthority);
    
    const signature = await this.connection.sendRawTransaction(tx.serialize());
    await this.connection.confirmTransaction(signature);
    
    return signature;
  }

  /**
   * Set campaign to LIVE state
   */
  async setLive(campaignId: bigint, startTs: number, endTs: number): Promise<string> {
    const [campaignPda] = getCampaignPDA(campaignId);

    const ix = await this.buildPlatformSetLiveIx(campaignPda, startTs, endTs);
    
    const tx = new Transaction().add(ix);
    tx.feePayer = this.platformAuthority.publicKey;
    tx.recentBlockhash = (await this.connection.getLatestBlockhash()).blockhash;
    
    tx.sign(this.platformAuthority);
    
    const signature = await this.connection.sendRawTransaction(tx.serialize());
    await this.connection.confirmTransaction(signature);
    
    return signature;
  }

  /**
   * Set campaign to EXPIRED state
   */
  async setExpired(campaignId: bigint): Promise<string> {
    const [campaignPda] = getCampaignPDA(campaignId);

    const ix = await this.buildPlatformSetExpiredIx(campaignPda);
    
    const tx = new Transaction().add(ix);
    tx.feePayer = this.platformAuthority.publicKey;
    tx.recentBlockhash = (await this.connection.getLatestBlockhash()).blockhash;
    
    tx.sign(this.platformAuthority);
    
    const signature = await this.connection.sendRawTransaction(tx.serialize());
    await this.connection.confirmTransaction(signature);
    
    return signature;
  }

  /**
   * Hard cancel campaign and refund sponsor
   */
  async hardCancelAndRefund(campaignId: bigint, sponsorPubkey: PublicKey): Promise<string> {
    const [campaignPda] = getCampaignPDA(campaignId);
    const [vaultPda] = getVaultPDA(campaignId);

    const ix = await this.buildPlatformHardCancelAndRefundIx(campaignPda, vaultPda, sponsorPubkey);
    
    const tx = new Transaction().add(ix);
    tx.feePayer = this.platformAuthority.publicKey;
    tx.recentBlockhash = (await this.connection.getLatestBlockhash()).blockhash;
    
    tx.sign(this.platformAuthority);
    
    const signature = await this.connection.sendRawTransaction(tx.serialize());
    await this.connection.confirmTransaction(signature);
    
    return signature;
  }

  /**
   * Fetch campaign account data
   */
  async fetchCampaign(campaignId: bigint): Promise<CampaignAccount | null> {
    const [campaignPda] = getCampaignPDA(campaignId);
    
    const accountInfo = await this.connection.getAccountInfo(campaignPda);
    if (!accountInfo) {
      return null;
    }

    // Parse account data (simplified - in production use Anchor's account decoder)
    // This is a placeholder - actual implementation would use the IDL
    return null;
  }

  // Instruction builders (simplified - in production these would use the full IDL)
  private async buildPlatformSetVerifyingIx(campaignPda: PublicKey) {
    // Discriminator for platform_set_verifying (first 8 bytes of sha256("global:platform_set_verifying"))
    const discriminator = Buffer.from([0x5e, 0x9c, 0x8d, 0x3f, 0x4a, 0x2b, 0x1c, 0x0d]);
    
    return {
      programId: PROGRAM_ID,
      keys: [
        { pubkey: this.platformAuthority.publicKey, isSigner: true, isWritable: false },
        { pubkey: campaignPda, isSigner: false, isWritable: true },
      ],
      data: discriminator,
    };
  }

  private async buildPlatformSetLiveIx(campaignPda: PublicKey, startTs: number, endTs: number) {
    const discriminator = Buffer.from([0x6f, 0xad, 0x9e, 0x4f, 0x5b, 0x3c, 0x2d, 0x1e]);
    const startTsBuf = Buffer.alloc(8);
    startTsBuf.writeBigInt64LE(BigInt(startTs));
    const endTsBuf = Buffer.alloc(8);
    endTsBuf.writeBigInt64LE(BigInt(endTs));
    
    return {
      programId: PROGRAM_ID,
      keys: [
        { pubkey: this.platformAuthority.publicKey, isSigner: true, isWritable: false },
        { pubkey: campaignPda, isSigner: false, isWritable: true },
      ],
      data: Buffer.concat([discriminator, startTsBuf, endTsBuf]),
    };
  }

  private async buildPlatformSetExpiredIx(campaignPda: PublicKey) {
    const discriminator = Buffer.from([0x7f, 0xbe, 0xaf, 0x5f, 0x6c, 0x4d, 0x3e, 0x2f]);
    
    return {
      programId: PROGRAM_ID,
      keys: [
        { pubkey: this.platformAuthority.publicKey, isSigner: true, isWritable: false },
        { pubkey: campaignPda, isSigner: false, isWritable: true },
      ],
      data: discriminator,
    };
  }

  private async buildPlatformHardCancelAndRefundIx(
    campaignPda: PublicKey,
    vaultPda: PublicKey,
    sponsorPubkey: PublicKey
  ) {
    const discriminator = Buffer.from([0x8f, 0xcf, 0xbf, 0x6f, 0x7d, 0x5e, 0x4f, 0x3f]);
    
    return {
      programId: PROGRAM_ID,
      keys: [
        { pubkey: this.platformAuthority.publicKey, isSigner: true, isWritable: false },
        { pubkey: campaignPda, isSigner: false, isWritable: true },
        { pubkey: vaultPda, isSigner: false, isWritable: true },
        { pubkey: sponsorPubkey, isSigner: false, isWritable: true },
      ],
      data: discriminator,
    };
  }
}

// Singleton instance
let clientInstance: BillboardMarketClient | null = null;

export function getBillboardClient(): BillboardMarketClient {
  if (!clientInstance) {
    clientInstance = new BillboardMarketClient();
  }
  return clientInstance;
}
