// This file will be populated after running `anchor build`
// The IDL (Interface Definition Language) is auto-generated by Anchor
// and describes the program's instructions, accounts, and types.

// For now, export a placeholder type
export type BillboardMarketIDL = {
  version: string;
  name: string;
  instructions: Array<{
    name: string;
    accounts: Array<{
      name: string;
      isMut: boolean;
      isSigner: boolean;
    }>;
    args: Array<{
      name: string;
      type: string;
    }>;
  }>;
  accounts: Array<{
    name: string;
    type: {
      kind: string;
      fields: Array<{
        name: string;
        type: string;
      }>;
    };
  }>;
  types: Array<{
    name: string;
    type: {
      kind: string;
      variants?: Array<{ name: string }>;
      fields?: Array<{ name: string; type: string }>;
    };
  }>;
  events: Array<{
    name: string;
    fields: Array<{
      name: string;
      type: string;
      index: boolean;
    }>;
  }>;
  errors: Array<{
    code: number;
    name: string;
    msg: string;
  }>;
};

// Placeholder IDL - replace with actual generated IDL after `anchor build`
export const IDL: BillboardMarketIDL = {
  version: '0.1.0',
  name: 'billboard_market',
  instructions: [],
  accounts: [],
  types: [],
  events: [],
  errors: [],
};
