/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BillboardMarket {
  export type CampaignStruct = {
    campaignId: BigNumberish;
    sponsor: AddressLike;
    creator: AddressLike;
    amount: BigNumberish;
    duration: BigNumberish;
    state: BigNumberish;
    startTs: BigNumberish;
    endTs: BigNumberish;
  };

  export type CampaignStructOutput = [
    campaignId: bigint,
    sponsor: string,
    creator: string,
    amount: bigint,
    duration: bigint,
    state: bigint,
    startTs: bigint,
    endTs: bigint
  ] & {
    campaignId: bigint;
    sponsor: string;
    creator: string;
    amount: bigint;
    duration: bigint;
    state: bigint;
    startTs: bigint;
    endTs: bigint;
  };
}

export interface BillboardMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "campaignExists"
      | "campaigns"
      | "createCampaignAndDeposit"
      | "creatorAccept"
      | "creatorClaim"
      | "creatorReject"
      | "getCampaign"
      | "owner"
      | "platformHardCancelAndRefund"
      | "platformSetExpired"
      | "platformSetLive"
      | "platformSetVerifying"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignAccepted"
      | "CampaignClaimed"
      | "CampaignCreated"
      | "CampaignExpired"
      | "CampaignHardCanceled"
      | "CampaignLive"
      | "CampaignRejected"
      | "CampaignVerifying"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "campaignExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaignAndDeposit",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorAccept",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorReject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformHardCancelAndRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformSetExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformSetLive",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformSetVerifying",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaignAndDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorAccept",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorReject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformHardCancelAndRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformSetExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformSetLive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformSetVerifying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CampaignAcceptedEvent {
  export type InputTuple = [campaignId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [campaignId: bigint, creator: string];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignClaimedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    sponsor: AddressLike,
    creator: AddressLike,
    amount: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    sponsor: string,
    creator: string,
    amount: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    sponsor: string;
    creator: string;
    amount: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignExpiredEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignHardCanceledEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    refundAmount: BigNumberish,
    sponsor: AddressLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    refundAmount: bigint,
    sponsor: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    refundAmount: bigint;
    sponsor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignLiveEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    startTs: BigNumberish,
    endTs: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    startTs: bigint,
    endTs: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    startTs: bigint;
    endTs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignRejectedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignVerifyingEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BillboardMarket extends BaseContract {
  connect(runner?: ContractRunner | null): BillboardMarket;
  waitForDeployment(): Promise<this>;

  interface: BillboardMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  campaignExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        campaignId: bigint;
        sponsor: string;
        creator: string;
        amount: bigint;
        duration: bigint;
        state: bigint;
        startTs: bigint;
        endTs: bigint;
      }
    ],
    "view"
  >;

  createCampaignAndDeposit: TypedContractMethod<
    [campaignId: BigNumberish, creator: AddressLike, duration: BigNumberish],
    [void],
    "payable"
  >;

  creatorAccept: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  creatorClaim: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  creatorReject: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [BillboardMarket.CampaignStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformHardCancelAndRefund: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformSetExpired: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformSetLive: TypedContractMethod<
    [campaignId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformSetVerifying: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "campaignExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        campaignId: bigint;
        sponsor: string;
        creator: string;
        amount: bigint;
        duration: bigint;
        state: bigint;
        startTs: bigint;
        endTs: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaignAndDeposit"
  ): TypedContractMethod<
    [campaignId: BigNumberish, creator: AddressLike, duration: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorAccept"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorClaim"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creatorReject"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [BillboardMarket.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformHardCancelAndRefund"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "platformSetExpired"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "platformSetLive"
  ): TypedContractMethod<
    [campaignId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformSetVerifying"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CampaignAccepted"
  ): TypedContractEvent<
    CampaignAcceptedEvent.InputTuple,
    CampaignAcceptedEvent.OutputTuple,
    CampaignAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignClaimed"
  ): TypedContractEvent<
    CampaignClaimedEvent.InputTuple,
    CampaignClaimedEvent.OutputTuple,
    CampaignClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignExpired"
  ): TypedContractEvent<
    CampaignExpiredEvent.InputTuple,
    CampaignExpiredEvent.OutputTuple,
    CampaignExpiredEvent.OutputObject
  >;
  getEvent(
    key: "CampaignHardCanceled"
  ): TypedContractEvent<
    CampaignHardCanceledEvent.InputTuple,
    CampaignHardCanceledEvent.OutputTuple,
    CampaignHardCanceledEvent.OutputObject
  >;
  getEvent(
    key: "CampaignLive"
  ): TypedContractEvent<
    CampaignLiveEvent.InputTuple,
    CampaignLiveEvent.OutputTuple,
    CampaignLiveEvent.OutputObject
  >;
  getEvent(
    key: "CampaignRejected"
  ): TypedContractEvent<
    CampaignRejectedEvent.InputTuple,
    CampaignRejectedEvent.OutputTuple,
    CampaignRejectedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignVerifying"
  ): TypedContractEvent<
    CampaignVerifyingEvent.InputTuple,
    CampaignVerifyingEvent.OutputTuple,
    CampaignVerifyingEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CampaignAccepted(uint256,address)": TypedContractEvent<
      CampaignAcceptedEvent.InputTuple,
      CampaignAcceptedEvent.OutputTuple,
      CampaignAcceptedEvent.OutputObject
    >;
    CampaignAccepted: TypedContractEvent<
      CampaignAcceptedEvent.InputTuple,
      CampaignAcceptedEvent.OutputTuple,
      CampaignAcceptedEvent.OutputObject
    >;

    "CampaignClaimed(uint256,address,uint256)": TypedContractEvent<
      CampaignClaimedEvent.InputTuple,
      CampaignClaimedEvent.OutputTuple,
      CampaignClaimedEvent.OutputObject
    >;
    CampaignClaimed: TypedContractEvent<
      CampaignClaimedEvent.InputTuple,
      CampaignClaimedEvent.OutputTuple,
      CampaignClaimedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignExpired(uint256)": TypedContractEvent<
      CampaignExpiredEvent.InputTuple,
      CampaignExpiredEvent.OutputTuple,
      CampaignExpiredEvent.OutputObject
    >;
    CampaignExpired: TypedContractEvent<
      CampaignExpiredEvent.InputTuple,
      CampaignExpiredEvent.OutputTuple,
      CampaignExpiredEvent.OutputObject
    >;

    "CampaignHardCanceled(uint256,uint256,address)": TypedContractEvent<
      CampaignHardCanceledEvent.InputTuple,
      CampaignHardCanceledEvent.OutputTuple,
      CampaignHardCanceledEvent.OutputObject
    >;
    CampaignHardCanceled: TypedContractEvent<
      CampaignHardCanceledEvent.InputTuple,
      CampaignHardCanceledEvent.OutputTuple,
      CampaignHardCanceledEvent.OutputObject
    >;

    "CampaignLive(uint256,uint64,uint64)": TypedContractEvent<
      CampaignLiveEvent.InputTuple,
      CampaignLiveEvent.OutputTuple,
      CampaignLiveEvent.OutputObject
    >;
    CampaignLive: TypedContractEvent<
      CampaignLiveEvent.InputTuple,
      CampaignLiveEvent.OutputTuple,
      CampaignLiveEvent.OutputObject
    >;

    "CampaignRejected(uint256,address,uint256)": TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;
    CampaignRejected: TypedContractEvent<
      CampaignRejectedEvent.InputTuple,
      CampaignRejectedEvent.OutputTuple,
      CampaignRejectedEvent.OutputObject
    >;

    "CampaignVerifying(uint256)": TypedContractEvent<
      CampaignVerifyingEvent.InputTuple,
      CampaignVerifyingEvent.OutputTuple,
      CampaignVerifyingEvent.OutputObject
    >;
    CampaignVerifying: TypedContractEvent<
      CampaignVerifyingEvent.InputTuple,
      CampaignVerifyingEvent.OutputTuple,
      CampaignVerifyingEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
